version: '3.8'

services:
  api-interseguro:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: always
    networks:
      - backend

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend: